export const  INCREMENT = 'INCREMENT'

export const DELETE_ITEM = 'DELETE_ITEM'

export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'

export const FILTER_SELECT = 'FILTER_SELECT'

export const FILTER_DATE_RANGE = 'FILTER_DATE_RANGE'

export const ADD_COMMENT = 'ADD_COMMENT'